export enum colouredIcon {
    list = "list-Colored-fill",
    table = "table-Colored-fill",
    crosstable = "crosstable-Colored-fill",
    bar = "bar-Colored-fill",
    pileBar = "pileBar-Colored-fill",
    percentPileBar = "percentPileBar-Colored-fill",
    stripe = "stripe-Colored-fill",
    pileStripe = "pileStripe-Colored-fill",
    percentPileStripe = "percentPileStripe-Colored-fill",
    line = "line-Colored-fill",
    area = "area-Colored-fill",
    biax = "biax-Colored-fill",
    funnel = "funnel-Colored-fill",
    funnelCompare = "funnelCompare-Colored-fill",
    card = "card-Colored-fill",
    progressBar = "progressBar-Colored-fill",
    gauge = "gauge-Colored-fill",
    pie = "pie-Colored-fill1",
    radar = "radar-Colored-fill",
    map = "map-Colored-fill",
    scatter = "scatter-Colored-fill"
}

export enum greyIcon  {
  list = "schedule-b-fill",
  table = "pivot-table-b-fill",
  crosstable = "crosstab-b-fill",
  bar = "histogram-b-fill",
  pileBar = "stacked-column-chart-b-fill",
  percentPileBar = "a-percentage-column-stacking-b-chart",
  stripe = "bar-chart-b-fill",
  pileStripe = "stacked-bar-b-fill",
  percentPileStripe = "a-percentage-column-bar-b-chart",
  line = "a-line-chart-b-fill",
  area = "area-map-b-fill",
  biax = "biaxial-graph-b-fill",
  funnel = "funnel-diagram-b-fill",
  funnelCompare = "comparison-funnel-b-fill",
  card = "Index-chart-b-fill",
  progressBar = "progress-chart-b-fill",
  gauge = "instrument-diagram-b-fill1",
  pie = "pie-doughnut-b-fill",
  radar = "radar-chart-b-fill",
  map = "map-Colored-fill",
  scatter = "scatter-diagram-b-fill"
}