export enum ToolsBarType {
  EXPORT = "elementExport",
  LINKAGE = "elementLinkage",
  REFRESH = "elementRefresh",
  NARROW = "elementNarrow",
  FULLSCREEN = "elementFullScreen",
  FILTER = "elementFilter",
  CUSTOMSQL = "customSql",
  SORT = "elementSort",
  EDIT = "elementEdit",
  REMOVE = "elementRemove",
  UPLOAD = "upload",
  DRAG = "elementDrag",
  LINE = "elementLine",
  COPY = " elementCopy",
  VISIBLE = "visible",
  EDITWEB = "editWeb",
  COMPARE = "compare",
  EDITIMAGE = 'editImage',
  RENAME = 'elementRename',
  EDITTAB = 'editTab',
  AIREMOVE = 'aiElementRemove',
  AITYPESET = 'aiElementTypeSet',
  AISAVE = 'aiElementSave',
  AIEXPORT = 'aiElementExport',
}
