export enum ReportAction {
  ADDELEMENT = "addElement", // 新增图表
  GETREPORTDETAIL = "getReportDetail", // 获取仪表盘明细
  GETREPORT = "getReport", // 获取仪表盘
  GETFILTERREPORT = "getFilterReport", //获取所有筛选仪表盘
  SAVEREPORT = "saveReport", // 保存仪表盘
  GENERATEREPORT = "generateReport", // 新生成仪表盘
  GETDATASOURCELIST = "getDataSourceList", // 获取数据源列表
  GETDATASOURCE = "getDataSource", // 获取数据源
  LOADDATASOURCE = "loadDataSource", // 加载数据源
  LOADCHARTDATA = "loadChartData", // 加载仪表盘图表数据
  SETCHARTLINKAGE = "setChartLinkage", // 设置图表联动
  SETFILTERPICKER = "setFilterPicker", // 设置过滤器条件
  REMOVEFILTERPICKER = "removeFilterPicker", // 删除过滤器条件
  REMOVEREPORT = "removeReport", // 删除仪表盘
  SETACTIVECHARTID = "setActiveChartId", // 设置当前激活的图表id
  REMOVESINGLECHART = "removeSingleChart", // 删除单个图表
  BETCHREMOVECHARTS = "betchRemoveCharts", // 批量删除图表
  UPDATESINGLECHART = "updateSingleChart", // 更新单个图表
  UPDATETABSERVER = "updateTabServer", // 更新tab图表
  UPDATESINGLECHARTTITLE = "updateSingleChartTitle", // 更新单个图表的标题
  ADDSINGLECHART = "addSingleChart", // 新增单个图表
  SETATTRIBUTES = "setAttributes", // 更新全局属性
  UPDATEGLOBALFILTER = "updateGlobalFilter", // 更新全局筛选器
  CHANGECHARTTYPE = "changeChartType", // 切换 图表类型
  UPDATEPOSITIONS = "updatePositions", // 批量更新图表位置
  UPDATEGLOBALSTYLES = "updateGlobalStyles", // 更新全局样式
  UPDATECHARTS = "updateCharts", // 更新全局样式 所有涉及到的图表
  SETDEFAULTGLOBAL = "setDefaultGlobal", // 更新全局样式
  SETCHARTLAYERLINK = "setChartLayerLink", // 设置图表下钻
  SETDESIGNLAYERLINK = "setDesignLayerLink", //设置设计界面的图表下钻
  UPDATEMOBILEOPTIONS = "updateMobileOptions", //移动端设计
  LOGTRACE = "logTrace", // 埋点
  GETCHARTS = "getCharts",
  GETADVANCEDLIST = "getAdvancedList",
  CHECKCOMPUTE = "checkCompute", //校验计算字段公式
  GETCONVERTREPORT = "getConvertReport", //获取转换后的仪表盘
  UPDATESQLPARAMSINGLOBAL = "updateSqlParamsInGlobal", // 更新动态参数--与全局筛选器保存逻辑一致,
  UPDATEGLOBALFILTERS = "updateGlobalFilters", // 更新全局筛选器--当已使用含动态参数的数据源的动参更新时,全局筛选器也要更新--仅处理动态参数相关
  UPDATESQLPARAMS = "updateSqlParams", // 通过加载后的数据源校验更新动态参数
}

export enum ReportMutation {
  INITREPORT = "initReport", //初始化报表数据
  SETENV = "setEnv", //设置环境
  SETCHARTS = "setCharts", // 设置图表
  SETGLOBAL = "setGlobal", // 设置仪表盘全局配置
  SETGLOBALSTYLEBYKEY = "setGlobalStyleByKey", // 设置仪表盘
  SETOBJECTID = "setObjectId", // 设置objectId
  SETTITLE = "setTitle", // 设置title
  SETREPORTTOP = "setReportTop", // 设置仪表盘的通用TOP
  SETREPORTTITLE = "setReportTitle", // 设置仪表盘标题
  SETACTIVECHART = "setActiveChart", // 设置激活的图表
  CLEARACTIVECHART = "clearActiveChart", // 清空激活的图表
  SETGLOBALFILTER = "setGlobalFilter", // 设置全局筛选条件
  HANDLESORT = "handleSort", // 处理排序字段
  SETDRAGCHART = "setDragChart", // 设置新增的图表实例
  SETDRAGFIELD = "setDragField", // 设置拖动中的字段
  SETREPORTOPTIONS = "setReportOptions", // 设置报表配置项
  CLEARCHARTRELATION = "clearChartRelation", // 清空图表关系
  CLEARCHARTANDFILTERRELATION = "clearChartAndFilterRelation", // 清空图表关系
  RESIZECHARTVIEW = "resizeChartView", // 刷新图表
  RESIZECHARTSVIEW = "resizeChartsView", // 刷新所有图表
  SETNUMBERFORMAT = "setNumberFormat", // 设置数据格式
  SETCONDITIONFORMAT = "setConditionFormat", // 设置条件格式
  SETRESULTFILTER = "setResultFilter", // 设置结果筛选器
  SETDATEFORMAT = "setDateFormat", // 设置明细表日期字段格式化
  HANDLESTYLES = "handleStyle",
  SETLASTDATASOURCE = "setLastDataSource", // 保存上一次数据源ID
  SETTABLEEXPORTDATA = "setTableExportData", // 保存透视表导出预处理数据
  DELETEMETRIC = "deleteMetric", // 删除指标
  SERINTROSTATE = "setIntroState", // 设置是否在新手新到
  SETCHARTSDATA = "setChartsData", // 设置图表数据
  SETADVANCEDATASOURCE = "setAdvancedDataSource", // 设置是否显示高级数据源
  CHANGEGLOBALTHEME = "changeGlobalTheme", // 改变全局皮肤
  RESERREPORT = "reSetReport", // 重置仪表盘
  UPDATEGLOBALFILTER = "updateGlobalFilter", // 更新全局筛选器
  ADDNEWELEMENT = "addNewElement", // 创建新的组件
  UPDATEACTIVECHART = "updateActiveChart", // 更新当前激活的图表数据
  SETROLEOPTIONS = "setRoleOptions", // 设置角色信息
  TOGGLEDESIGNMODE = "toggleDesignMode", // 切换编辑模式
  ADDORUPDATECHART = "addOrUpdateChart", // 新增或更新chart
  UPDATETABMAPPING = "updateTabMapping", // 新增或更新chart
  UPDATEMOBILETABMAP = "updateMobileTabMap", // 更新移动端tab映射,移动端筛选过滤组件
  CLEARTABCHART = "clearTabChart", // 取消新增时,删除tab内多余图表
  SETRELATIONCHART = "setRelationChart", //设置chart relation 关系图
  UPDATERELATIONCHART = "updateRelationChart", // 更新下钻关系图
  DELETERELATIONCHART = "deleteRelationChart", // 删除下钻关系图
  SETACTIVECHARTLAYERSBYID = "setActiveChartLayers", // 根据id设置当前正在编辑的图层数组
  UPDATEACTIVECHARTLAYERS = "updateActiveChartLayers", //更新正在编辑的图层数组数据，
  UPDATECHARTLAYERSDATA = "updateChartLayersData", // 切换图层后更新正在编辑的图层数据
  UPDATELAYERFILTER = "updateLayerFilter", // 点击切换下钻更新图层,
  SETCHARTINTERVAL = "setChartInterval", // 设置定时器
  CLEARCHARTINTERVAL = "clearChartInterval", // 清空定时器
  SETFULLSTATUS = "setFullStatus", //设置全屏状态
  SETFORECAST = "setForecast", //设置预测功能显示隐藏
  SETTARGETVALUE = "setTargetValue", // 设置目标值格式
  SYNCCUTOMSORT = "syncCustomSort", // 同步维度的自定义排序
  SYNCDIMENSIONSORT = "syncDimensionSort", //同步自定义排序维度中的isCustomer
  SYNCCOMPAREDATA = "syncCompareData", //同步对比数据的代码
  CHANGESWITCHLAYERS = "changeSwitchLayers", //修改图层切换
  SETLANGTYPE = "setLangType", //修改语言
  AddLOG = "addLog", // 新增埋点
  SAVELOG = "saveLog", // 缓存埋点
  SETCHARTSRENAME = 'setChartsRename',
  SETCHARTSREVERT = 'setChartsRevert',
  COMBINECHARTS = "combineCharts", // 切换图层后重新合并图表
  CLEARCHARTSRELATION = "clearChartsRelation", // 清空图表关系
  SETCHARTSRELATIONINTAB = "setChartsRelationIntab", // 设置图表关系
  SETCONVERTREPORTINFO = "setConvertReportInfo", // 设置转换后的仪表盘信息
}
